using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyCompanyAttribute("Igor Brejc and others")]
[assembly: AssemblyProductAttribute("Srtm2Osm")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2007-2022 Igor Brejc and others")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyFileVersionAttribute("1.15.4.0")]
[assembly: AssemblyInformationalVersionAttribute("1.15")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyNameAttribute("")]

